{
    "active_lock_reason": null,
    "assignee": null,
    "assignees": [],
    "author_association": "NONE",
    "body": "### Describe the bug\r\n\r\nI am not able to get neovim to detect python 3 on Windows 11 pro. I made several attempts.\r\n\r\n1)\r\n- installed python 3.10 (and also 3.7 after uninstalling 3.10) from the Microsoft Store\r\n- installed neovim 0.8.2 via chocolatey\r\n- followed the guide https://neovim.io/doc/user/provider.html + stackoverlow question and answers. I am sure I used correct path, keys, etc.\r\n\r\nnvim has never detected a python provider able to import neovim (tested within several shells)\r\n\r\n2)\r\n- uninstalled python got via the MS app store\r\n- installed python 3.11 via chocolatey\r\nsame results sa above.\r\n\r\nEvery time I ran `:checkhealth` and got this:\r\n```\r\n## Python 3 provider (optional)\r\n  - INFO: Using: g:python3_host_prog = \"C:/Python311/python.exe\"\r\n  - WARNING: No Python executable found that can `import neovim`. Using the first available executable for diagnostics.\r\n  - INFO: Executable: Not found\r\n\r\n## Python virtualenv\r\n  - OK: no $VIRTUAL_ENV\r\n```\r\nThis last message corresponds to the attempt with choco installation.\r\n\r\nBut then I can:\r\n```\r\nC:\\>python --version\r\nPython 3.11.0\r\n\r\nC:\\>python\r\nPython 3.11.0 (main, Oct 24 2022, 18:26:48) [MSC v.1933 64 bit (AMD64)] on win32\r\nType \"help\", \"copyright\", \"credits\" or \"license\" for more information.\r\n>>> import neovim\r\n>>> import pynvim\r\n>>> print(neovim.__file__)\r\nC:\\Users\\user\\AppData\\Roaming\\Python\\Python311\\site-packages\\neovim\\__init__.py\r\n>>> print(pynvim.__file__)\r\nC:\\Users\\user\\AppData\\Roaming\\Python\\Python311\\site-packages\\pynvim\\__init__.py\r\n```\r\n\r\nNOTE:  In all cases I also uninstalled and reinstalled neovim via chocolatey. I tried to specify the path with /, \\\\, etc. single quotes double quotes. I think I did not leave anything untested.\r\n\r\nIn ALL cases, in all shells I could just execute `python` and `import neovim` or `import pynvim` without issues (as shown above)\r\n\r\nIf neovim on windows is supposed to detect python, I think there is a bug somewhere.\r\n\r\n\r\n\r\n\r\n### Steps to reproduce\r\n\r\nDescribed above. Basically follow the instructions to use python with neovim.\r\n\r\n### Expected behavior\r\n\r\nI would expect neovim to detect the python provider\r\n\r\n\r\n### Neovim version (nvim -v)\r\n\r\n0.8.3\r\n\r\n### Vim (not Nvim) behaves the same?\r\n\r\nnot installed\r\n\r\n### Operating system/version\r\n\r\nWindows 11\r\n\r\n### Terminal name/version\r\n\r\nWindows Terminal, git bash, command promp, powershell\r\n\r\n### $TERM environment variable\r\n\r\nnone\r\n\r\n### Installation\r\n\r\nchoco / windows store",
    "closed_at": null,
    "closed_by": {
        "avatar_url": "https://avatars.githubusercontent.com/u/7904185?v=4",
        "events_url": "https://api.github.com/users/lewis6991/events{/privacy}",
        "followers_url": "https://api.github.com/users/lewis6991/followers",
        "following_url": "https://api.github.com/users/lewis6991/following{/other_user}",
        "gists_url": "https://api.github.com/users/lewis6991/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/lewis6991",
        "id": 7904185,
        "login": "lewis6991",
        "node_id": "MDQ6VXNlcjc5MDQxODU=",
        "organizations_url": "https://api.github.com/users/lewis6991/orgs",
        "received_events_url": "https://api.github.com/users/lewis6991/received_events",
        "repos_url": "https://api.github.com/users/lewis6991/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/lewis6991/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/lewis6991/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/lewis6991",
        "user_view_type": "public"
    },
    "comment_data": [
        {
            "author_association": "NONE",
            "body": "Neovim doesn't detect python (for me, should it?), but you can set it explicitly by setting `g:python3_host_prog` in your Lua configuration as it says in the `:checkhealth` output. So this is probably not a bug, please read `:h g:python3_host_prog` or [make a Google search](https://www.google.com/search?q=g%3Apython3_host_prog).",
            "created_at": "2023-02-04T16:16:20Z",
            "html_url": "https://github.com/neovim/neovim/issues/22117#issuecomment-1416791950",
            "id": 1416791950,
            "issue_url": "https://api.github.com/repos/neovim/neovim/issues/22117",
            "node_id": "IC_kwDOAPphoM5UcoeO",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/neovim/neovim/issues/comments/1416791950/reactions"
            },
            "updated_at": "2023-02-04T16:17:47Z",
            "url": "https://api.github.com/repos/neovim/neovim/issues/comments/1416791950",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/24259245?v=4",
                "events_url": "https://api.github.com/users/martin-braun/events{/privacy}",
                "followers_url": "https://api.github.com/users/martin-braun/followers",
                "following_url": "https://api.github.com/users/martin-braun/following{/other_user}",
                "gists_url": "https://api.github.com/users/martin-braun/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/martin-braun",
                "id": 24259245,
                "login": "martin-braun",
                "node_id": "MDQ6VXNlcjI0MjU5MjQ1",
                "organizations_url": "https://api.github.com/users/martin-braun/orgs",
                "received_events_url": "https://api.github.com/users/martin-braun/received_events",
                "repos_url": "https://api.github.com/users/martin-braun/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/martin-braun/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/martin-braun/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/martin-braun",
                "user_view_type": "public"
            }
        },
        {
            "author_association": "NONE",
            "body": "I did, it was in the output of `:checkhealth()` (see above):\r\n```\r\nINFO: Using: g:python3_host_prog = \"C:/Python311/python.exe\"\r\n```\r\ni.e., where chocolatey installed it.\r\n\r\n As I said, I followed all the instructions.",
            "created_at": "2023-02-04T17:00:07Z",
            "html_url": "https://github.com/neovim/neovim/issues/22117#issuecomment-1416800342",
            "id": 1416800342,
            "issue_url": "https://api.github.com/repos/neovim/neovim/issues/22117",
            "node_id": "IC_kwDOAPphoM5UcqhW",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/neovim/neovim/issues/comments/1416800342/reactions"
            },
            "updated_at": "2023-02-04T17:02:45Z",
            "url": "https://api.github.com/repos/neovim/neovim/issues/comments/1416800342",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/6717655?v=4",
                "events_url": "https://api.github.com/users/thistlillo/events{/privacy}",
                "followers_url": "https://api.github.com/users/thistlillo/followers",
                "following_url": "https://api.github.com/users/thistlillo/following{/other_user}",
                "gists_url": "https://api.github.com/users/thistlillo/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/thistlillo",
                "id": 6717655,
                "login": "thistlillo",
                "node_id": "MDQ6VXNlcjY3MTc2NTU=",
                "organizations_url": "https://api.github.com/users/thistlillo/orgs",
                "received_events_url": "https://api.github.com/users/thistlillo/received_events",
                "repos_url": "https://api.github.com/users/thistlillo/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/thistlillo/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/thistlillo/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/thistlillo",
                "user_view_type": "public"
            }
        },
        {
            "author_association": "NONE",
            "body": "Have you installed the [Neovim provider for Python](https://pypi.org/project/neovim/)? `pip install neovim`",
            "created_at": "2023-02-04T19:21:31Z",
            "html_url": "https://github.com/neovim/neovim/issues/22117#issuecomment-1416830701",
            "id": 1416830701,
            "issue_url": "https://api.github.com/repos/neovim/neovim/issues/22117",
            "node_id": "IC_kwDOAPphoM5Ucx7t",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/neovim/neovim/issues/comments/1416830701/reactions"
            },
            "updated_at": "2023-02-04T19:21:31Z",
            "url": "https://api.github.com/repos/neovim/neovim/issues/comments/1416830701",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/24259245?v=4",
                "events_url": "https://api.github.com/users/martin-braun/events{/privacy}",
                "followers_url": "https://api.github.com/users/martin-braun/followers",
                "following_url": "https://api.github.com/users/martin-braun/following{/other_user}",
                "gists_url": "https://api.github.com/users/martin-braun/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/martin-braun",
                "id": 24259245,
                "login": "martin-braun",
                "node_id": "MDQ6VXNlcjI0MjU5MjQ1",
                "organizations_url": "https://api.github.com/users/martin-braun/orgs",
                "received_events_url": "https://api.github.com/users/martin-braun/received_events",
                "repos_url": "https://api.github.com/users/martin-braun/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/martin-braun/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/martin-braun/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/martin-braun",
                "user_view_type": "public"
            }
        },
        {
            "author_association": "NONE",
            "body": "Yes, I did.\r\n\r\n```\r\nC:\\>python\r\nPython 3.11.0 (main, Oct 24 2022, 18:26:48) [MSC v.1933 64 bit (AMD64)] on win32\r\nType \"help\", \"copyright\", \"credits\" or \"license\" for more information.\r\n>>> import neovim\r\n>>> import pynvim\r\n>>> print(neovim.__file__)\r\nC:\\Users\\user\\AppData\\Roaming\\Python\\Python311\\site-packages\\neovim\\__init__.py\r\n>>> print(pynvim.__file__)\r\nC:\\Users\\user\\AppData\\Roaming\\Python\\Python311\\site-packages\\pynvim\\__init__.py\r\n```\r\n\r\nHowever, yesterday night I ended up uninstalling everything. I will make another attempt over the next weekends. In my initial message I did not show the content of `C:/Python311/` but I can assure you it was the correct path, `python.exe` was there.",
            "created_at": "2023-02-05T06:19:54Z",
            "html_url": "https://github.com/neovim/neovim/issues/22117#issuecomment-1416933063",
            "id": 1416933063,
            "issue_url": "https://api.github.com/repos/neovim/neovim/issues/22117",
            "node_id": "IC_kwDOAPphoM5UdK7H",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/neovim/neovim/issues/comments/1416933063/reactions"
            },
            "updated_at": "2023-02-05T06:28:03Z",
            "url": "https://api.github.com/repos/neovim/neovim/issues/comments/1416933063",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/6717655?v=4",
                "events_url": "https://api.github.com/users/thistlillo/events{/privacy}",
                "followers_url": "https://api.github.com/users/thistlillo/followers",
                "following_url": "https://api.github.com/users/thistlillo/following{/other_user}",
                "gists_url": "https://api.github.com/users/thistlillo/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/thistlillo",
                "id": 6717655,
                "login": "thistlillo",
                "node_id": "MDQ6VXNlcjY3MTc2NTU=",
                "organizations_url": "https://api.github.com/users/thistlillo/orgs",
                "received_events_url": "https://api.github.com/users/thistlillo/received_events",
                "repos_url": "https://api.github.com/users/thistlillo/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/thistlillo/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/thistlillo/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/thistlillo",
                "user_view_type": "public"
            }
        },
        {
            "author_association": "NONE",
            "body": "@thistlillo If it doesn't work in the next attempt, you can always try to troubleshoot within Neovim by doing `:! command` as if you were in your normal Windows Prompt.",
            "created_at": "2023-02-05T22:45:17Z",
            "html_url": "https://github.com/neovim/neovim/issues/22117#issuecomment-1418285664",
            "id": 1418285664,
            "issue_url": "https://api.github.com/repos/neovim/neovim/issues/22117",
            "node_id": "IC_kwDOAPphoM5UiVJg",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/neovim/neovim/issues/comments/1418285664/reactions"
            },
            "updated_at": "2023-02-05T22:45:17Z",
            "url": "https://api.github.com/repos/neovim/neovim/issues/comments/1418285664",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/24259245?v=4",
                "events_url": "https://api.github.com/users/martin-braun/events{/privacy}",
                "followers_url": "https://api.github.com/users/martin-braun/followers",
                "following_url": "https://api.github.com/users/martin-braun/following{/other_user}",
                "gists_url": "https://api.github.com/users/martin-braun/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/martin-braun",
                "id": 24259245,
                "login": "martin-braun",
                "node_id": "MDQ6VXNlcjI0MjU5MjQ1",
                "organizations_url": "https://api.github.com/users/martin-braun/orgs",
                "received_events_url": "https://api.github.com/users/martin-braun/received_events",
                "repos_url": "https://api.github.com/users/martin-braun/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/martin-braun/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/martin-braun/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/martin-braun",
                "user_view_type": "public"
            }
        },
        {
            "author_association": "CONTRIBUTOR",
            "body": "I cannot reproduce this bug.  Should be closed.  OP can re-open if they still experience it.",
            "created_at": "2023-02-15T13:21:08Z",
            "html_url": "https://github.com/neovim/neovim/issues/22117#issuecomment-1431361378",
            "id": 1431361378,
            "issue_url": "https://api.github.com/repos/neovim/neovim/issues/22117",
            "node_id": "IC_kwDOAPphoM5VUNdi",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/neovim/neovim/issues/comments/1431361378/reactions"
            },
            "updated_at": "2023-02-15T13:21:08Z",
            "url": "https://api.github.com/repos/neovim/neovim/issues/comments/1431361378",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/32037751?v=4",
                "events_url": "https://api.github.com/users/3N4N/events{/privacy}",
                "followers_url": "https://api.github.com/users/3N4N/followers",
                "following_url": "https://api.github.com/users/3N4N/following{/other_user}",
                "gists_url": "https://api.github.com/users/3N4N/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/3N4N",
                "id": 32037751,
                "login": "3N4N",
                "node_id": "MDQ6VXNlcjMyMDM3NzUx",
                "organizations_url": "https://api.github.com/users/3N4N/orgs",
                "received_events_url": "https://api.github.com/users/3N4N/received_events",
                "repos_url": "https://api.github.com/users/3N4N/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/3N4N/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/3N4N/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/3N4N",
                "user_view_type": "public"
            }
        },
        {
            "author_association": "NONE",
            "body": "Sorry, but I have not tried again. I will keep you updated.",
            "created_at": "2023-02-15T21:26:58Z",
            "html_url": "https://github.com/neovim/neovim/issues/22117#issuecomment-1432055997",
            "id": 1432055997,
            "issue_url": "https://api.github.com/repos/neovim/neovim/issues/22117",
            "node_id": "IC_kwDOAPphoM5VW3C9",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/neovim/neovim/issues/comments/1432055997/reactions"
            },
            "updated_at": "2023-02-15T21:26:58Z",
            "url": "https://api.github.com/repos/neovim/neovim/issues/comments/1432055997",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/6717655?v=4",
                "events_url": "https://api.github.com/users/thistlillo/events{/privacy}",
                "followers_url": "https://api.github.com/users/thistlillo/followers",
                "following_url": "https://api.github.com/users/thistlillo/following{/other_user}",
                "gists_url": "https://api.github.com/users/thistlillo/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/thistlillo",
                "id": 6717655,
                "login": "thistlillo",
                "node_id": "MDQ6VXNlcjY3MTc2NTU=",
                "organizations_url": "https://api.github.com/users/thistlillo/orgs",
                "received_events_url": "https://api.github.com/users/thistlillo/received_events",
                "repos_url": "https://api.github.com/users/thistlillo/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/thistlillo/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/thistlillo/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/thistlillo",
                "user_view_type": "public"
            }
        },
        {
            "author_association": "NONE",
            "body": "For the following friends who might have the same problem and find this post:\r\nI followed exactly all the steps I should, but the problem was still there. \r\n\r\nWindows 11\r\nPython: 3.11\r\npynvim: 0.4.3\r\nnvim: 0.9\r\n\r\nI have the problem fixed by installing my python through the [official site](https://www.python.org/downloads/). Before I installed through installers like Microsoft store, tried different versions of python, not working.",
            "created_at": "2023-05-11T21:55:02Z",
            "html_url": "https://github.com/neovim/neovim/issues/22117#issuecomment-1544736111",
            "id": 1544736111,
            "issue_url": "https://api.github.com/repos/neovim/neovim/issues/22117",
            "node_id": "IC_kwDOAPphoM5cEs1v",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 1,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 1,
                "url": "https://api.github.com/repos/neovim/neovim/issues/comments/1544736111/reactions"
            },
            "updated_at": "2023-05-11T21:55:02Z",
            "url": "https://api.github.com/repos/neovim/neovim/issues/comments/1544736111",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/34515663?v=4",
                "events_url": "https://api.github.com/users/resort09/events{/privacy}",
                "followers_url": "https://api.github.com/users/resort09/followers",
                "following_url": "https://api.github.com/users/resort09/following{/other_user}",
                "gists_url": "https://api.github.com/users/resort09/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/resort09",
                "id": 34515663,
                "login": "resort09",
                "node_id": "MDQ6VXNlcjM0NTE1NjYz",
                "organizations_url": "https://api.github.com/users/resort09/orgs",
                "received_events_url": "https://api.github.com/users/resort09/received_events",
                "repos_url": "https://api.github.com/users/resort09/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/resort09/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/resort09/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/resort09",
                "user_view_type": "public"
            }
        },
        {
            "author_association": "NONE",
            "body": "The same problem:\r\n\r\nPython 3 provider (optional)\r\n- WARNING No Python executable found that can `import neovim`. Using the first available executable for diagnostics.\r\n- WARNING Could not load Python 3:\r\n  python3 not found in search path or not executable.\r\n  python3.10 not found in search path or not executable.\r\n  python3.9 not found in search path or not executable.\r\n  python3.8 not found in search path or not executable.\r\n  python3.7 not found in search path or not executable.\r\n  python not found in search path or not executable.\r\n  - ADVICE:\r\n    - See :help provider-python for more information.\r\n    - You may disable this provider (and warning) by adding let g:loaded_python3_provider = 0 to your init.vim\r\n- Executable: Not found\r\n\r\nPython3 is in path an can be started from the same CMD window where Nvim has been started\r\n\r\nWindows11\r\nPuthon 3.11 from Microsoft Store",
            "created_at": "2023-11-21T09:13:11Z",
            "html_url": "https://github.com/neovim/neovim/issues/22117#issuecomment-1820516215",
            "id": 1820516215,
            "issue_url": "https://api.github.com/repos/neovim/neovim/issues/22117",
            "node_id": "IC_kwDOAPphoM5sgt93",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/neovim/neovim/issues/comments/1820516215/reactions"
            },
            "updated_at": "2023-11-21T14:37:12Z",
            "url": "https://api.github.com/repos/neovim/neovim/issues/comments/1820516215",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/11873804?v=4",
                "events_url": "https://api.github.com/users/KarlikB/events{/privacy}",
                "followers_url": "https://api.github.com/users/KarlikB/followers",
                "following_url": "https://api.github.com/users/KarlikB/following{/other_user}",
                "gists_url": "https://api.github.com/users/KarlikB/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/KarlikB",
                "id": 11873804,
                "login": "KarlikB",
                "node_id": "MDQ6VXNlcjExODczODA0",
                "organizations_url": "https://api.github.com/users/KarlikB/orgs",
                "received_events_url": "https://api.github.com/users/KarlikB/received_events",
                "repos_url": "https://api.github.com/users/KarlikB/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/KarlikB/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/KarlikB/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/KarlikB",
                "user_view_type": "public"
            }
        },
        {
            "author_association": "NONE",
            "body": "I had the same issue. Python was installed. `python` in the CLI worked, but neovim could not detect python, even when explicitly pointed to the path.\r\nThe problem was the version of python from the microsoft store.\r\nInstalling python directly from https://www.python.org/downloads/ and pointing neovim to that install using `g:python3_host_prog` resolved the issue.",
            "created_at": "2024-03-02T03:32:45Z",
            "html_url": "https://github.com/neovim/neovim/issues/22117#issuecomment-1974253245",
            "id": 1974253245,
            "issue_url": "https://api.github.com/repos/neovim/neovim/issues/22117",
            "node_id": "IC_kwDOAPphoM51rLa9",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/neovim/neovim/issues/comments/1974253245/reactions"
            },
            "updated_at": "2024-03-02T03:32:45Z",
            "url": "https://api.github.com/repos/neovim/neovim/issues/comments/1974253245",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/4077188?v=4",
                "events_url": "https://api.github.com/users/dylanrenwick/events{/privacy}",
                "followers_url": "https://api.github.com/users/dylanrenwick/followers",
                "following_url": "https://api.github.com/users/dylanrenwick/following{/other_user}",
                "gists_url": "https://api.github.com/users/dylanrenwick/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/dylanrenwick",
                "id": 4077188,
                "login": "dylanrenwick",
                "node_id": "MDQ6VXNlcjQwNzcxODg=",
                "organizations_url": "https://api.github.com/users/dylanrenwick/orgs",
                "received_events_url": "https://api.github.com/users/dylanrenwick/received_events",
                "repos_url": "https://api.github.com/users/dylanrenwick/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/dylanrenwick/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/dylanrenwick/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/dylanrenwick",
                "user_view_type": "public"
            }
        },
        {
            "author_association": "NONE",
            "body": "So I cracked the 'code' on this bug. Using the `python3.exe` or `python3.11.exe` found in $PATH (eg. `C:\\Users\\cam\\AppData\\Local\\Microsoft\\WindowsApps\\python3.11.exe` ) doesn't work. This is due to those files being 0 byte `reparse points` used by Windows 10. \r\n\r\nChecking for ourselves we can see:\r\n```\r\nC:\\Users\\cam\\AppData\\Local\\Microsoft\\WindowsApps>fsutil reparsepoint /?\r\n/? is an invalid parameter.\r\n---- REPARSEPOINT Commands Supported ----\r\n\r\ndelete          Delete a reparse point\r\nquery           Query a reparse point\r\n\r\nC:\\Users\\cam\\AppData\\Local\\Microsoft\\WindowsApps>fsutil reparsepoint query python.exe\r\nReparse Tag Value : 0x8000001b\r\nTag value: Microsoft\r\n\r\nReparse Data Length: 0x1c2\r\nReparse Data:\r\n0000:  03 00 00 00 50 00 79 00  74 00 68 00 6f 00 6e 00  ....P.y.t.h.o.n.\r\n0010:  53 00 6f 00 66 00 74 00  77 00 61 00 72 00 65 00  S.o.f.t.w.a.r.e.\r\n0020:  46 00 6f 00 75 00 6e 00  64 00 61 00 74 00 69 00  F.o.u.n.d.a.t.i.\r\n0030:  6f 00 6e 00 2e 00 50 00  79 00 74 00 68 00 6f 00  o.n...P.y.t.h.o.\r\n0040:  6e 00 2e 00 33 00 2e 00  31 00 31 00 5f 00 71 00  n...3...1.1._.q.\r\n0050:  62 00 7a 00 35 00 6e 00  32 00 6b 00 66 00 72 00  b.z.5.n.2.k.f.r.\r\n0060:  61 00 38 00 70 00 30 00  00 00 50 00 79 00 74 00  a.8.p.0...P.y.t.\r\n0070:  68 00 6f 00 6e 00 53 00  6f 00 66 00 74 00 77 00  h.o.n.S.o.f.t.w.\r\n0080:  61 00 72 00 65 00 46 00  6f 00 75 00 6e 00 64 00  a.r.e.F.o.u.n.d.\r\n0090:  61 00 74 00 69 00 6f 00  6e 00 2e 00 50 00 79 00  a.t.i.o.n...P.y.\r\n00a0:  74 00 68 00 6f 00 6e 00  2e 00 33 00 2e 00 31 00  t.h.o.n...3...1.\r\n00b0:  31 00 5f 00 71 00 62 00  7a 00 35 00 6e 00 32 00  1._.q.b.z.5.n.2.\r\n00c0:  6b 00 66 00 72 00 61 00  38 00 70 00 30 00 21 00  k.f.r.a.8.p.0.!.\r\n00d0:  50 00 79 00 74 00 68 00  6f 00 6e 00 00 00 43 00  P.y.t.h.o.n...C.\r\n00e0:  3a 00 5c 00 50 00 72 00  6f 00 67 00 72 00 61 00  :.\\.P.r.o.g.r.a.\r\n00f0:  6d 00 20 00 46 00 69 00  6c 00 65 00 73 00 5c 00  m. .F.i.l.e.s.\\.\r\n0100:  57 00 69 00 6e 00 64 00  6f 00 77 00 73 00 41 00  W.i.n.d.o.w.s.A.\r\n0110:  70 00 70 00 73 00 5c 00  50 00 79 00 74 00 68 00  p.p.s.\\.P.y.t.h.\r\n0120:  6f 00 6e 00 53 00 6f 00  66 00 74 00 77 00 61 00  o.n.S.o.f.t.w.a.\r\n0130:  72 00 65 00 46 00 6f 00  75 00 6e 00 64 00 61 00  r.e.F.o.u.n.d.a.\r\n0140:  74 00 69 00 6f 00 6e 00  2e 00 50 00 79 00 74 00  t.i.o.n...P.y.t.\r\n0150:  68 00 6f 00 6e 00 2e 00  33 00 2e 00 31 00 31 00  h.o.n...3...1.1.\r\n0160:  5f 00 33 00 2e 00 31 00  31 00 2e 00 32 00 32 00  _.3...1.1...2.2.\r\n0170:  38 00 38 00 2e 00 30 00  5f 00 78 00 36 00 34 00  8.8...0._.x.6.4.\r\n0180:  5f 00 5f 00 71 00 62 00  7a 00 35 00 6e 00 32 00  _._.q.b.z.5.n.2.\r\n0190:  6b 00 66 00 72 00 61 00  38 00 70 00 30 00 5c 00  k.f.r.a.8.p.0.\\.\r\n01a0:  70 00 79 00 74 00 68 00  6f 00 6e 00 33 00 2e 00  p.y.t.h.o.n.3...\r\n01b0:  31 00 31 00 2e 00 65 00  78 00 65 00 00 00 30 00  1.1...e.x.e...0.\r\n01c0:  00 00\r\n```\r\n\r\nThe cheap fix is to update the neovim variable to the proper (non-zero sized exe):\r\n```\r\nlet g:python3_host_prog = 'C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.11_3.11.2288.0_x64__qbz5n2kfra8p0\\python3.11.exe'\r\n```\r\nThe downside is imagine the path will change when ever a update is provided from the Microsoft Store.\r\n\r\nThe long term fix is probably with the neovim dev to help the Window lusers out by accomidating for this.\r\n\r\nHope that helps other users and the devs.",
            "created_at": "2024-03-06T05:06:24Z",
            "html_url": "https://github.com/neovim/neovim/issues/22117#issuecomment-1980095820",
            "id": 1980095820,
            "issue_url": "https://api.github.com/repos/neovim/neovim/issues/22117",
            "node_id": "IC_kwDOAPphoM52Bd1M",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 3,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 3,
                "url": "https://api.github.com/repos/neovim/neovim/issues/comments/1980095820/reactions"
            },
            "updated_at": "2024-03-06T05:06:24Z",
            "url": "https://api.github.com/repos/neovim/neovim/issues/comments/1980095820",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/2858315?v=4",
                "events_url": "https://api.github.com/users/camAtGitHub/events{/privacy}",
                "followers_url": "https://api.github.com/users/camAtGitHub/followers",
                "following_url": "https://api.github.com/users/camAtGitHub/following{/other_user}",
                "gists_url": "https://api.github.com/users/camAtGitHub/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/camAtGitHub",
                "id": 2858315,
                "login": "camAtGitHub",
                "node_id": "MDQ6VXNlcjI4NTgzMTU=",
                "organizations_url": "https://api.github.com/users/camAtGitHub/orgs",
                "received_events_url": "https://api.github.com/users/camAtGitHub/received_events",
                "repos_url": "https://api.github.com/users/camAtGitHub/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/camAtGitHub/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/camAtGitHub/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/camAtGitHub",
                "user_view_type": "public"
            }
        },
        {
            "author_association": "NONE",
            "body": "@camAtGitHub  Hi there I have experience the same problem with 3.12 could you give me some help with this?",
            "created_at": "2024-06-20T04:51:21Z",
            "html_url": "https://github.com/neovim/neovim/issues/22117#issuecomment-2179804476",
            "id": 2179804476,
            "issue_url": "https://api.github.com/repos/neovim/neovim/issues/22117",
            "node_id": "IC_kwDOAPphoM6B7S08",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/neovim/neovim/issues/comments/2179804476/reactions"
            },
            "updated_at": "2024-06-20T04:51:21Z",
            "url": "https://api.github.com/repos/neovim/neovim/issues/comments/2179804476",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/113310442?v=4",
                "events_url": "https://api.github.com/users/JDCerberus/events{/privacy}",
                "followers_url": "https://api.github.com/users/JDCerberus/followers",
                "following_url": "https://api.github.com/users/JDCerberus/following{/other_user}",
                "gists_url": "https://api.github.com/users/JDCerberus/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/JDCerberus",
                "id": 113310442,
                "login": "JDCerberus",
                "node_id": "U_kgDOBsD66g",
                "organizations_url": "https://api.github.com/users/JDCerberus/orgs",
                "received_events_url": "https://api.github.com/users/JDCerberus/received_events",
                "repos_url": "https://api.github.com/users/JDCerberus/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/JDCerberus/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/JDCerberus/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/JDCerberus",
                "user_view_type": "public"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "This seems fixed in Vim in https://github.com/vim/vim/commit/40fd7e665260c9227d6d90b17a301a1bc47f7f5b",
            "created_at": "2024-08-08T02:56:38Z",
            "html_url": "https://github.com/neovim/neovim/issues/22117#issuecomment-2274857859",
            "id": 2274857859,
            "issue_url": "https://api.github.com/repos/neovim/neovim/issues/22117",
            "node_id": "IC_kwDOAPphoM6Hl5OD",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/neovim/neovim/issues/comments/2274857859/reactions"
            },
            "updated_at": "2024-08-08T02:56:38Z",
            "url": "https://api.github.com/repos/neovim/neovim/issues/comments/2274857859",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/35768171?v=4",
                "events_url": "https://api.github.com/users/zeertzjq/events{/privacy}",
                "followers_url": "https://api.github.com/users/zeertzjq/followers",
                "following_url": "https://api.github.com/users/zeertzjq/following{/other_user}",
                "gists_url": "https://api.github.com/users/zeertzjq/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/zeertzjq",
                "id": 35768171,
                "login": "zeertzjq",
                "node_id": "MDQ6VXNlcjM1NzY4MTcx",
                "organizations_url": "https://api.github.com/users/zeertzjq/orgs",
                "received_events_url": "https://api.github.com/users/zeertzjq/received_events",
                "repos_url": "https://api.github.com/users/zeertzjq/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/zeertzjq/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/zeertzjq/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/zeertzjq",
                "user_view_type": "public"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "This is a general issue with \"Microsoft/WindowsApps/...\" paths:\n\n- https://github.com/neovim/neovim/issues/34596",
            "created_at": "2025-06-23T09:03:49Z",
            "html_url": "https://github.com/neovim/neovim/issues/22117#issuecomment-2995583265",
            "id": 2995583265,
            "issue_url": "https://api.github.com/repos/neovim/neovim/issues/22117",
            "node_id": "IC_kwDOAPphoM6yjPkh",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/neovim/neovim/issues/comments/2995583265/reactions"
            },
            "updated_at": "2025-06-23T09:03:49Z",
            "url": "https://api.github.com/repos/neovim/neovim/issues/comments/2995583265",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/1359421?v=4",
                "events_url": "https://api.github.com/users/justinmk/events{/privacy}",
                "followers_url": "https://api.github.com/users/justinmk/followers",
                "following_url": "https://api.github.com/users/justinmk/following{/other_user}",
                "gists_url": "https://api.github.com/users/justinmk/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/justinmk",
                "id": 1359421,
                "login": "justinmk",
                "node_id": "MDQ6VXNlcjEzNTk0MjE=",
                "organizations_url": "https://api.github.com/users/justinmk/orgs",
                "received_events_url": "https://api.github.com/users/justinmk/received_events",
                "repos_url": "https://api.github.com/users/justinmk/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/justinmk/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/justinmk/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/justinmk",
                "user_view_type": "public"
            }
        }
    ],
    "comments": 14,
    "comments_url": "https://api.github.com/repos/neovim/neovim/issues/22117/comments",
    "created_at": "2023-02-04T14:01:45Z",
    "events_url": "https://api.github.com/repos/neovim/neovim/issues/22117/events",
    "html_url": "https://github.com/neovim/neovim/issues/22117",
    "id": 1570956169,
    "labels": [
        {
            "color": "d4c5f9",
            "default": false,
            "description": null,
            "id": 109461219,
            "name": "platform:windows",
            "node_id": "MDU6TGFiZWwxMDk0NjEyMTk=",
            "url": "https://api.github.com/repos/neovim/neovim/labels/platform:windows"
        },
        {
            "color": "c5def5",
            "default": false,
            "description": null,
            "id": 144672485,
            "name": "provider",
            "node_id": "MDU6TGFiZWwxNDQ2NzI0ODU=",
            "url": "https://api.github.com/repos/neovim/neovim/labels/provider"
        },
        {
            "color": "0E8A16",
            "default": false,
            "description": "issue is fixed in vim and patch needs to be ported",
            "id": 152276149,
            "name": "has:vim-patch",
            "node_id": "MDU6TGFiZWwxNTIyNzYxNDk=",
            "url": "https://api.github.com/repos/neovim/neovim/labels/has:vim-patch"
        },
        {
            "color": "C5DEF5",
            "default": false,
            "description": "file metadata/attributes, filenames, path manipulation",
            "id": 3386070083,
            "name": "filesystem",
            "node_id": "LA_kwDOAPphoM7J01RD",
            "url": "https://api.github.com/repos/neovim/neovim/labels/filesystem"
        }
    ],
    "labels_url": "https://api.github.com/repos/neovim/neovim/issues/22117/labels{/name}",
    "locked": false,
    "milestone": {
        "closed_at": null,
        "closed_issues": 726,
        "created_at": "2014-05-10T20:43:04Z",
        "creator": {
            "avatar_url": "https://avatars.githubusercontent.com/u/1359421?v=4",
            "events_url": "https://api.github.com/users/justinmk/events{/privacy}",
            "followers_url": "https://api.github.com/users/justinmk/followers",
            "following_url": "https://api.github.com/users/justinmk/following{/other_user}",
            "gists_url": "https://api.github.com/users/justinmk/gists{/gist_id}",
            "gravatar_id": "",
            "html_url": "https://github.com/justinmk",
            "id": 1359421,
            "login": "justinmk",
            "node_id": "MDQ6VXNlcjEzNTk0MjE=",
            "organizations_url": "https://api.github.com/users/justinmk/orgs",
            "received_events_url": "https://api.github.com/users/justinmk/received_events",
            "repos_url": "https://api.github.com/users/justinmk/repos",
            "site_admin": false,
            "starred_url": "https://api.github.com/users/justinmk/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/justinmk/subscriptions",
            "type": "User",
            "url": "https://api.github.com/users/justinmk",
            "user_view_type": "public"
        },
        "description": "Low priority items. We plan to work on this but don't have a target date.",
        "due_on": null,
        "html_url": "https://github.com/neovim/neovim/milestone/6",
        "id": 655037,
        "labels_url": "https://api.github.com/repos/neovim/neovim/milestones/6/labels",
        "node_id": "MDk6TWlsZXN0b25lNjU1MDM3",
        "number": 6,
        "open_issues": 630,
        "state": "open",
        "title": "backlog",
        "updated_at": "2025-07-07T03:51:31Z",
        "url": "https://api.github.com/repos/neovim/neovim/milestones/6"
    },
    "node_id": "I_kwDOAPphoM5douOJ",
    "number": 22117,
    "performed_via_github_app": null,
    "reactions": {
        "+1": 0,
        "-1": 0,
        "confused": 0,
        "eyes": 0,
        "heart": 0,
        "hooray": 0,
        "laugh": 0,
        "rocket": 0,
        "total_count": 0,
        "url": "https://api.github.com/repos/neovim/neovim/issues/22117/reactions"
    },
    "repository_url": "https://api.github.com/repos/neovim/neovim",
    "state": "open",
    "state_reason": "reopened",
    "sub_issues_summary": {
        "completed": 0,
        "percent_completed": 0,
        "total": 0
    },
    "timeline_url": "https://api.github.com/repos/neovim/neovim/issues/22117/timeline",
    "title": "neovim does not detect python on Windows 11",
    "type": {
        "color": "red",
        "created_at": "2024-01-25T10:10:19Z",
        "description": "An unexpected problem or behavior",
        "id": 597163,
        "is_enabled": true,
        "name": "Bug",
        "node_id": "IT_kwDOAGK_Pc4ACRyr",
        "updated_at": "2024-07-26T10:12:30Z"
    },
    "updated_at": "2025-07-02T08:38:28Z",
    "url": "https://api.github.com/repos/neovim/neovim/issues/22117",
    "user": {
        "avatar_url": "https://avatars.githubusercontent.com/u/6717655?v=4",
        "events_url": "https://api.github.com/users/thistlillo/events{/privacy}",
        "followers_url": "https://api.github.com/users/thistlillo/followers",
        "following_url": "https://api.github.com/users/thistlillo/following{/other_user}",
        "gists_url": "https://api.github.com/users/thistlillo/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/thistlillo",
        "id": 6717655,
        "login": "thistlillo",
        "node_id": "MDQ6VXNlcjY3MTc2NTU=",
        "organizations_url": "https://api.github.com/users/thistlillo/orgs",
        "received_events_url": "https://api.github.com/users/thistlillo/received_events",
        "repos_url": "https://api.github.com/users/thistlillo/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/thistlillo/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/thistlillo/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/thistlillo",
        "user_view_type": "public"
    }
}