{
    "active_lock_reason": null,
    "assignee": null,
    "assignees": [],
    "author_association": "NONE",
    "body": "### Problem\n\nI tried to move my config to 0.11 with the new deprecation of vim.fn.sign_define into vim.diagnostic.config.\nI am running into the issue that with the new way to configure the signs, signs are displaying on Linux but not on MacOS arm64.\nThe icons are not displaying with the new way to configure. I tried on 0.10.4 and 0.11 and the problem is the same on both. I am not sure if something is different with the MacOS configuration vs the Linux one since on Linux the signs are displaying correctly but on MacOS it only displays the first letter of the type (eg. W for warning).\n\nI am wondering if there is a way to check if the config is loading properly on Mac for that special `vim.diagnostic.config` because it seems to load fine on Linux.\n\nThanks for the help on that one!\n\nThis is the old way on MacOS:\n<img width=\"503\" alt=\"Image\" src=\"https://github.com/user-attachments/assets/25530e11-11ed-4e1a-9637-46af5f1efbdb\" />\n\nThis is the new way on MacOS:\n<img width=\"554\" alt=\"Image\" src=\"https://github.com/user-attachments/assets/952da7d7-5497-43a8-ad9f-1319e1a43798\" />\n\nThis is on Linux (old and new way to configure signs):\n<img width=\"268\" alt=\"Image\" src=\"https://github.com/user-attachments/assets/3d332f33-6c53-42c8-ae15-a51b0563c841\" />\n\n\nThis was the old config which is now raising warning:\n```\nlocal signs = { Error = \" \", Warn = \" \", Hint = \"ﴞ \", Info = \" \" }\nfor type, icon in pairs(signs) do\n        local hl = \"DiagnosticSign\" .. type\n        vim.fn.sign_define(hl, { text = icon, texthl = hl, numhl = \"\" })\nend\n```\nI moved it to:\n```\nvim.diagnostic.config({\n        signs = {\n                text = {\n                        [vim.diagnostic.severity.ERROR] = \" \",\n                        [vim.diagnostic.severity.WARN] = \" \",\n                        [vim.diagnostic.severity.INFO] = \"󰋼 \",\n                        [vim.diagnostic.severity.HINT] = \"󰌵 \",\n                },\n                texthl = {\n                        [vim.diagnostic.severity.ERROR] = \"Error\",\n                        [vim.diagnostic.severity.WARN] = \"Error\",\n                        [vim.diagnostic.severity.HINT] = \"Hint\",\n                        [vim.diagnostic.severity.INFO] = \"Info\",\n                },\n                numhl = {\n                        [vim.diagnostic.severity.ERROR] = \"\",\n                        [vim.diagnostic.severity.WARN] = \"\",\n                        [vim.diagnostic.severity.HINT] = \"\",\n                        [vim.diagnostic.severity.INFO] = \"\",\n                },\n        },\n})\n```\n\nFull config is available [here](https://gitlab.com/loicdiridollou/configuration-files/-/blob/main/nvim/lua/plugins/lsp_config.lua?ref_type=heads).\n\n\n### Steps to reproduce\n\nConfigure the diagnostic with the config above on MacOS arm64.\n\n### Expected behavior\n\nIcons should display like the old behavior and not have the first letter for each severity.\n\n### Nvim version (nvim -v)\n\nNVIM v0.11.0\n\n### Vim (not Nvim) behaves the same?\n\nDid not try\n\n### Operating system/version\n\nmacOs 15.3.2\n\n### Terminal name/version\n\nGhostty 1.0\n\n### $TERM environment variable\n\nxterm-ghostty\n\n### Installation\n\nhomebrew",
    "closed_at": "2025-03-29T11:33:34Z",
    "closed_by": {
        "avatar_url": "https://avatars.githubusercontent.com/u/1359421?v=4",
        "events_url": "https://api.github.com/users/justinmk/events{/privacy}",
        "followers_url": "https://api.github.com/users/justinmk/followers",
        "following_url": "https://api.github.com/users/justinmk/following{/other_user}",
        "gists_url": "https://api.github.com/users/justinmk/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/justinmk",
        "id": 1359421,
        "login": "justinmk",
        "node_id": "MDQ6VXNlcjEzNTk0MjE=",
        "organizations_url": "https://api.github.com/users/justinmk/orgs",
        "received_events_url": "https://api.github.com/users/justinmk/received_events",
        "repos_url": "https://api.github.com/users/justinmk/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/justinmk/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/justinmk/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/justinmk",
        "user_view_type": "public"
    },
    "comment_data": [
        {
            "author_association": "MEMBER",
            "body": "> This was the old config which is now raising warning:\n\nWhat is the warning message?\n\n> it seems to load fine on Linux.\n\nHow did you install Nvim on Linux?",
            "created_at": "2025-03-29T00:39:14Z",
            "html_url": "https://github.com/neovim/neovim/issues/33144#issuecomment-2762942895",
            "id": 2762942895,
            "issue_url": "https://api.github.com/repos/neovim/neovim/issues/33144",
            "node_id": "IC_kwDOAPphoM6krymv",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/neovim/neovim/issues/comments/2762942895/reactions"
            },
            "updated_at": "2025-03-29T00:39:51Z",
            "url": "https://api.github.com/repos/neovim/neovim/issues/comments/2762942895",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/35768171?v=4",
                "events_url": "https://api.github.com/users/zeertzjq/events{/privacy}",
                "followers_url": "https://api.github.com/users/zeertzjq/followers",
                "following_url": "https://api.github.com/users/zeertzjq/following{/other_user}",
                "gists_url": "https://api.github.com/users/zeertzjq/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/zeertzjq",
                "id": 35768171,
                "login": "zeertzjq",
                "node_id": "MDQ6VXNlcjM1NzY4MTcx",
                "organizations_url": "https://api.github.com/users/zeertzjq/orgs",
                "received_events_url": "https://api.github.com/users/zeertzjq/received_events",
                "repos_url": "https://api.github.com/users/zeertzjq/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/zeertzjq/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/zeertzjq/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/zeertzjq",
                "user_view_type": "public"
            }
        },
        {
            "author_association": "NONE",
            "body": "The warning that I get using the old way to define the signs `vim.fn.sign_define` is the following deprecation message:\n`Defining diagnostic signs with :sign-define or sign_define() is deprecated. Run \":check...`\nOn Linux I am using the appimage directly.",
            "created_at": "2025-03-29T01:04:03Z",
            "html_url": "https://github.com/neovim/neovim/issues/33144#issuecomment-2762958899",
            "id": 2762958899,
            "issue_url": "https://api.github.com/repos/neovim/neovim/issues/33144",
            "node_id": "IC_kwDOAPphoM6kr2gz",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/neovim/neovim/issues/comments/2762958899/reactions"
            },
            "updated_at": "2025-03-29T01:04:03Z",
            "url": "https://api.github.com/repos/neovim/neovim/issues/comments/2762958899",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/52484416?v=4",
                "events_url": "https://api.github.com/users/loicdiridollou/events{/privacy}",
                "followers_url": "https://api.github.com/users/loicdiridollou/followers",
                "following_url": "https://api.github.com/users/loicdiridollou/following{/other_user}",
                "gists_url": "https://api.github.com/users/loicdiridollou/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/loicdiridollou",
                "id": 52484416,
                "login": "loicdiridollou",
                "node_id": "MDQ6VXNlcjUyNDg0NDE2",
                "organizations_url": "https://api.github.com/users/loicdiridollou/orgs",
                "received_events_url": "https://api.github.com/users/loicdiridollou/received_events",
                "repos_url": "https://api.github.com/users/loicdiridollou/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/loicdiridollou/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/loicdiridollou/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/loicdiridollou",
                "user_view_type": "public"
            }
        },
        {
            "author_association": "NONE",
            "body": "`texthl` is an invalid key, just delete it. \n\nThis warning occues because we do not need to do `sign_define` for diagnostic signs, which should be placed in `vim.diagnostic.config({ signs = {}})`. texthl is done internally: `vim.diagnostic.severity.ERROR` use highligh group `DiagnosticSignError`, and `DiagnosticSignError` is link to `DiagnosticError` by default, same to WARN, INFO, HINT.\n\nBy the way, according to Screenshot, highlight is good.\n\n```lua\nvim.diagnostic.config({\n        signs = {\n                text = {\n                        [vim.diagnostic.severity.ERROR] = \" \",\n                        [vim.diagnostic.severity.WARN] = \" \",\n                        [vim.diagnostic.severity.INFO] = \"󰋼 \",\n                        [vim.diagnostic.severity.HINT] = \"󰌵 \",\n                },\n                numhl = {\n                        [vim.diagnostic.severity.ERROR] = \"\",\n                        [vim.diagnostic.severity.WARN] = \"\",\n                        [vim.diagnostic.severity.HINT] = \"\",\n                        [vim.diagnostic.severity.INFO] = \"\",\n                },\n        },\n})\n```\n\nSign text is not correct on macos, try rebuild neovim in macos. make sure delete old runtime files. `/usr/local/share/nvim/runtime/` before you do `make install`.",
            "created_at": "2025-03-29T09:40:12Z",
            "html_url": "https://github.com/neovim/neovim/issues/33144#issuecomment-2763257650",
            "id": 2763257650,
            "issue_url": "https://api.github.com/repos/neovim/neovim/issues/33144",
            "node_id": "IC_kwDOAPphoM6ks_cy",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 1,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 2,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 3,
                "url": "https://api.github.com/repos/neovim/neovim/issues/comments/2763257650/reactions"
            },
            "updated_at": "2025-03-29T09:40:12Z",
            "url": "https://api.github.com/repos/neovim/neovim/issues/comments/2763257650",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/7881849?v=4",
                "events_url": "https://api.github.com/users/xieyonn/events{/privacy}",
                "followers_url": "https://api.github.com/users/xieyonn/followers",
                "following_url": "https://api.github.com/users/xieyonn/following{/other_user}",
                "gists_url": "https://api.github.com/users/xieyonn/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/xieyonn",
                "id": 7881849,
                "login": "xieyonn",
                "node_id": "MDQ6VXNlcjc4ODE4NDk=",
                "organizations_url": "https://api.github.com/users/xieyonn/orgs",
                "received_events_url": "https://api.github.com/users/xieyonn/received_events",
                "repos_url": "https://api.github.com/users/xieyonn/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/xieyonn/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/xieyonn/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/xieyonn",
                "user_view_type": "public"
            }
        },
        {
            "author_association": "NONE",
            "body": "Hey @xieyonn,\nThanks a lot for the feedback here, indeed my config was correct but the issue was how `ray-x/go.nvim` was interacting with the config. It was working on Linux because my config was not loading any go package since go was not configured on the Linux machine, but it was loading on MacOS thus causing the issue.\nAll makes sense, sorry to have caused some work here, really appreciate you jumping in on this one!",
            "created_at": "2025-03-29T18:07:58Z",
            "html_url": "https://github.com/neovim/neovim/issues/33144#issuecomment-2763949262",
            "id": 2763949262,
            "issue_url": "https://api.github.com/repos/neovim/neovim/issues/33144",
            "node_id": "IC_kwDOAPphoM6kvoTO",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 1,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 1,
                "url": "https://api.github.com/repos/neovim/neovim/issues/comments/2763949262/reactions"
            },
            "updated_at": "2025-03-29T18:37:38Z",
            "url": "https://api.github.com/repos/neovim/neovim/issues/comments/2763949262",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/52484416?v=4",
                "events_url": "https://api.github.com/users/loicdiridollou/events{/privacy}",
                "followers_url": "https://api.github.com/users/loicdiridollou/followers",
                "following_url": "https://api.github.com/users/loicdiridollou/following{/other_user}",
                "gists_url": "https://api.github.com/users/loicdiridollou/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/loicdiridollou",
                "id": 52484416,
                "login": "loicdiridollou",
                "node_id": "MDQ6VXNlcjUyNDg0NDE2",
                "organizations_url": "https://api.github.com/users/loicdiridollou/orgs",
                "received_events_url": "https://api.github.com/users/loicdiridollou/received_events",
                "repos_url": "https://api.github.com/users/loicdiridollou/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/loicdiridollou/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/loicdiridollou/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/loicdiridollou",
                "user_view_type": "public"
            }
        },
        {
            "author_association": "NONE",
            "body": "I was also confused by this error at first, so I searched and found this issue. After checking the documentation, I finally understood what was going on. :)",
            "created_at": "2025-03-29T18:37:05Z",
            "html_url": "https://github.com/neovim/neovim/issues/33144#issuecomment-2764026278",
            "id": 2764026278,
            "issue_url": "https://api.github.com/repos/neovim/neovim/issues/33144",
            "node_id": "IC_kwDOAPphoM6kv7Gm",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/neovim/neovim/issues/comments/2764026278/reactions"
            },
            "updated_at": "2025-03-29T18:37:43Z",
            "url": "https://api.github.com/repos/neovim/neovim/issues/comments/2764026278",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/7881849?v=4",
                "events_url": "https://api.github.com/users/xieyonn/events{/privacy}",
                "followers_url": "https://api.github.com/users/xieyonn/followers",
                "following_url": "https://api.github.com/users/xieyonn/following{/other_user}",
                "gists_url": "https://api.github.com/users/xieyonn/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/xieyonn",
                "id": 7881849,
                "login": "xieyonn",
                "node_id": "MDQ6VXNlcjc4ODE4NDk=",
                "organizations_url": "https://api.github.com/users/xieyonn/orgs",
                "received_events_url": "https://api.github.com/users/xieyonn/received_events",
                "repos_url": "https://api.github.com/users/xieyonn/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/xieyonn/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/xieyonn/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/xieyonn",
                "user_view_type": "public"
            }
        }
    ],
    "comments": 5,
    "comments_url": "https://api.github.com/repos/neovim/neovim/issues/33144/comments",
    "created_at": "2025-03-29T00:20:02Z",
    "events_url": "https://api.github.com/repos/neovim/neovim/issues/33144/events",
    "html_url": "https://github.com/neovim/neovim/issues/33144",
    "id": 2957560036,
    "labels": [
        {
            "color": "e6e6e6",
            "default": false,
            "description": "issues that are closed as usage questions",
            "id": 77997478,
            "name": "closed:question",
            "node_id": "MDU6TGFiZWw3Nzk5NzQ3OA==",
            "url": "https://api.github.com/repos/neovim/neovim/labels/closed:question"
        },
        {
            "color": "C5DEF5",
            "default": false,
            "description": "",
            "id": 3361645105,
            "name": "diagnostic",
            "node_id": "MDU6TGFiZWwzMzYxNjQ1MTA1",
            "url": "https://api.github.com/repos/neovim/neovim/labels/diagnostic"
        }
    ],
    "labels_url": "https://api.github.com/repos/neovim/neovim/issues/33144/labels{/name}",
    "locked": false,
    "milestone": null,
    "node_id": "I_kwDOAPphoM6wSMjk",
    "number": 33144,
    "performed_via_github_app": null,
    "reactions": {
        "+1": 0,
        "-1": 0,
        "confused": 0,
        "eyes": 0,
        "heart": 0,
        "hooray": 0,
        "laugh": 0,
        "rocket": 0,
        "total_count": 0,
        "url": "https://api.github.com/repos/neovim/neovim/issues/33144/reactions"
    },
    "repository_url": "https://api.github.com/repos/neovim/neovim",
    "state": "closed",
    "state_reason": "completed",
    "sub_issues_summary": {
        "completed": 0,
        "percent_completed": 0,
        "total": 0
    },
    "timeline_url": "https://api.github.com/repos/neovim/neovim/issues/33144/timeline",
    "title": "Issue displaying signs for error/hint/warning/info with new vim.diagnostic.config instead of vim.fn.sign_define",
    "type": null,
    "updated_at": "2025-03-29T22:38:03Z",
    "url": "https://api.github.com/repos/neovim/neovim/issues/33144",
    "user": {
        "avatar_url": "https://avatars.githubusercontent.com/u/52484416?v=4",
        "events_url": "https://api.github.com/users/loicdiridollou/events{/privacy}",
        "followers_url": "https://api.github.com/users/loicdiridollou/followers",
        "following_url": "https://api.github.com/users/loicdiridollou/following{/other_user}",
        "gists_url": "https://api.github.com/users/loicdiridollou/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/loicdiridollou",
        "id": 52484416,
        "login": "loicdiridollou",
        "node_id": "MDQ6VXNlcjUyNDg0NDE2",
        "organizations_url": "https://api.github.com/users/loicdiridollou/orgs",
        "received_events_url": "https://api.github.com/users/loicdiridollou/received_events",
        "repos_url": "https://api.github.com/users/loicdiridollou/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/loicdiridollou/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/loicdiridollou/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/loicdiridollou",
        "user_view_type": "public"
    }
}