{
    "active_lock_reason": null,
    "assignee": null,
    "assignees": [],
    "author_association": "CONTRIBUTOR",
    "body": "### Problem\n\nSince #33723  plugin tar oldtest is broken in master. \n\nI've tried debugging why `vim.diagnostic.status()` in the statusline breaks oldtest, specifically `test_plugin_tar.vim`\n\nthere are 2 errors in master currently\n\nhttps://github.com/neovim/neovim/blob/c3a4d125296caaf15ff424e7609e731a8b4d37e7/test/old/testdir/test_plugin_tar.vim#L34\n\n```\nFound errors in Test_tar_basic():\nCaught exception in Test_tar_basic(): Vim(append):Lua callback: vim/filetype.lua:0: module 'vim.filetype.detect' not found:     no field package.preload['vim.filetype.detect'] no file './vim/filetype/detect.lua'    no file '/Users/antonk52/Documents/dev/personal/neovim/.deps/usr/share/luajit-2.1/vim/filetype/detect.lua'      no file '/usr/local/share/lua/5.1/vim/filetype/detect.lua'       no file '/usr/local/share/lua/5.1/vim/filetype/detect/init.lua' no file '/Users/antonk52/Documents/dev/personal/neovim/.deps/usr/share/lua/5.1/vim/filetype/detect.lua' no file '/Users/antonk52/Documents/dev/personal/neovim/.deps/usr/share/lua/5.1/vim/filetype/detect/init.lua'    no file './vim/filetype/detect.so'      no file '/usr/local/lib/lua/5.1/vim/filetype/detect.so' no file '/Users/antonk52/Documents/dev/personal/neovim/.deps/usr/lib/lua/5.1/vim/filetype/detect.so'    no file '/usr/local/lib/lua/5.1/loadall.so'     no file './vim.so'      no file '/usr/local/lib/lua/5.1/vim.so' no file '/Users/antonk52/Documents/dev/personal/neovim/.deps/usr/lib/lua/5.1/vim.so'    no file '/usr/local/lib/lua/5.1/loadall.so'stack traceback:     [C]: in function 'require'      vim/filetype.lua: in function <vim/filetype.lua:0>     vim/filetype.lua: in function '' vim/filetype.lua: in function 'match'   ...onk52/Documents/dev/personal/neovim/runtime/filetype.lua:14: in function <...onk52/Documents/dev/personal/neovim/runtime/filetype.lua:10> @ command line..script /Users/antonk52/Documents/dev/personal/neovim/test/old/testdir/runtest.vim[652]..function RunTheTest[61]..Test_tar_basic[21]..<SNR>10_TarBrowseSelect[28]..BufReadPost Autocommands for \"*\"\n```\n\nand \n\nhttps://github.com/neovim/neovim/blob/c3a4d125296caaf15ff424e7609e731a8b4d37e7/test/old/testdir/test_plugin_tar.vim#L90\n\n```\nFound errors in Test_tar_evil():\nCaught exception in Test_tar_evil(): Vim(append):Lua callback: vim/filetype.lua:0: module 'vim.filetype.detect' not found:      no field package.preload['vim.filetype.detect'] no file './vim/filetype/detect.lua'    no file '/Users/antonk52/Documents/dev/personal/neovim/.deps/usr/share/luajit-2.1/vim/filetype/detect.lua'      no file '/usr/local/share/lua/5.1/vim/filetype/detect.lua'       no file '/usr/local/share/lua/5.1/vim/filetype/detect/init.lua' no file '/Users/antonk52/Documents/dev/personal/neovim/.deps/usr/share/lua/5.1/vim/filetype/detect.lua' no file '/Users/antonk52/Documents/dev/personal/neovim/.deps/usr/share/lua/5.1/vim/filetype/detect/init.lua'    no file './vim/filetype/detect.so'      no file '/usr/local/lib/lua/5.1/vim/filetype/detect.so' no file '/Users/antonk52/Documents/dev/personal/neovim/.deps/usr/lib/lua/5.1/vim/filetype/detect.so'    no file '/usr/local/lib/lua/5.1/loadall.so'     no file './vim.so'      no file '/usr/local/lib/lua/5.1/vim.so' no file '/Users/antonk52/Documents/dev/personal/neovim/.deps/usr/lib/lua/5.1/vim.so'    no file '/usr/local/lib/lua/5.1/loadall.so'stack traceback:     [C]: in function 'require'      vim/filetype.lua: in function 'match'   ...onk52/Documents/dev/personal/neovim/runtime/filetype.lua:14: in function <...onk52/Documents/dev/personal/neovim/runtime/filetype.lua:10> @ command line..script /Users/antonk52/Documents/dev/personal/neovim/test/old/testdir/runtest.vim[652]..function RunTheTest[61]..Test_tar_evil[22]..<SNR>10_TarBrowseSelect[28]..BufReadPost Autocommands for \"*\"\n```\n\nI was not able to identify why it fails to load vim.filetype.detect. As a result I see two ways of fixing the tests so the github actions in master and other pull requests are green again\n\n1. add `set statusline=''` to both tests in `test_plugin_tar.vim` - this way it is no longer affected by the statusline content, which I guess also makes it less of an e2e test. [branch](https://github.com/antonk52/neovim/tree/f/fix-oldtests-stub-statusline)\n2. remove vim.diagnostic.status from the statusline, we can still keep the vim.diagnostic.status function. [branch](https://github.com/antonk52/neovim/tree/f/fix-oldtests)\n\nOldtests pass for both of these. Happy to make a PR for either but wanted to get some thoughts on which one is preferred\n\n### Steps to reproduce\n\nmake oldtest TEST_FILE=test_plugin_tar.vim\n\n### Expected behavior\n\nTests pass\n\n### Nvim version (nvim -v)\n\nN/A\n\n### Vim (not Nvim) behaves the same?\n\nN/A\n\n### Operating system/version\n\nmacOS\n\n### Terminal name/version\n\nN/A\n\n### $TERM environment variable\n\nN/A\n\n### Installation\n\ngit clone https://github.com/neovim/neovim.git",
    "closed_at": "2025-08-02T09:51:42Z",
    "closed_by": {
        "avatar_url": "https://avatars.githubusercontent.com/u/1363104?v=4",
        "events_url": "https://api.github.com/users/bfredl/events{/privacy}",
        "followers_url": "https://api.github.com/users/bfredl/followers",
        "following_url": "https://api.github.com/users/bfredl/following{/other_user}",
        "gists_url": "https://api.github.com/users/bfredl/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/bfredl",
        "id": 1363104,
        "login": "bfredl",
        "node_id": "MDQ6VXNlcjEzNjMxMDQ=",
        "organizations_url": "https://api.github.com/users/bfredl/orgs",
        "received_events_url": "https://api.github.com/users/bfredl/received_events",
        "repos_url": "https://api.github.com/users/bfredl/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/bfredl/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/bfredl/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/bfredl",
        "user_view_type": "public"
    },
    "comment_data": [
        {
            "author_association": "MEMBER",
            "body": "I think there is bug in `nvim__get_runtime` that causes `require('vim.diagnostic')` to fail under some circumstances, and even makes some subsequent `require()` calls to also fail.",
            "created_at": "2025-08-02T06:51:43Z",
            "html_url": "https://github.com/neovim/neovim/issues/35124#issuecomment-3146275241",
            "id": 3146275241,
            "issue_url": "https://api.github.com/repos/neovim/neovim/issues/35124",
            "node_id": "IC_kwDOAPphoM67iFmp",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/neovim/neovim/issues/comments/3146275241/reactions"
            },
            "updated_at": "2025-08-02T06:51:43Z",
            "url": "https://api.github.com/repos/neovim/neovim/issues/comments/3146275241",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/35768171?v=4",
                "events_url": "https://api.github.com/users/zeertzjq/events{/privacy}",
                "followers_url": "https://api.github.com/users/zeertzjq/followers",
                "following_url": "https://api.github.com/users/zeertzjq/following{/other_user}",
                "gists_url": "https://api.github.com/users/zeertzjq/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/zeertzjq",
                "id": 35768171,
                "login": "zeertzjq",
                "node_id": "MDQ6VXNlcjM1NzY4MTcx",
                "organizations_url": "https://api.github.com/users/zeertzjq/orgs",
                "received_events_url": "https://api.github.com/users/zeertzjq/received_events",
                "repos_url": "https://api.github.com/users/zeertzjq/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/zeertzjq/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/zeertzjq/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/zeertzjq",
                "user_view_type": "public"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "There is some underlying bug, but we should not load `vim.diagnostic` just to observe that the module is not used anyway, see #35135 ",
            "created_at": "2025-08-02T08:58:42Z",
            "html_url": "https://github.com/neovim/neovim/issues/35124#issuecomment-3146374821",
            "id": 3146374821,
            "issue_url": "https://api.github.com/repos/neovim/neovim/issues/35124",
            "node_id": "IC_kwDOAPphoM67id6l",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/neovim/neovim/issues/comments/3146374821/reactions"
            },
            "updated_at": "2025-08-02T08:58:42Z",
            "url": "https://api.github.com/repos/neovim/neovim/issues/comments/3146374821",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/1363104?v=4",
                "events_url": "https://api.github.com/users/bfredl/events{/privacy}",
                "followers_url": "https://api.github.com/users/bfredl/followers",
                "following_url": "https://api.github.com/users/bfredl/following{/other_user}",
                "gists_url": "https://api.github.com/users/bfredl/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/bfredl",
                "id": 1363104,
                "login": "bfredl",
                "node_id": "MDQ6VXNlcjEzNjMxMDQ=",
                "organizations_url": "https://api.github.com/users/bfredl/orgs",
                "received_events_url": "https://api.github.com/users/bfredl/received_events",
                "repos_url": "https://api.github.com/users/bfredl/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/bfredl/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/bfredl/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/bfredl",
                "user_view_type": "public"
            }
        }
    ],
    "comments": 2,
    "comments_url": "https://api.github.com/repos/neovim/neovim/issues/35124/comments",
    "created_at": "2025-08-01T00:01:10Z",
    "events_url": "https://api.github.com/repos/neovim/neovim/issues/35124/events",
    "html_url": "https://github.com/neovim/neovim/issues/35124",
    "id": 3282030481,
    "labels": [],
    "labels_url": "https://api.github.com/repos/neovim/neovim/issues/35124/labels{/name}",
    "locked": false,
    "milestone": null,
    "node_id": "I_kwDOAPphoM7Dn8-R",
    "number": 35124,
    "performed_via_github_app": null,
    "reactions": {
        "+1": 0,
        "-1": 0,
        "confused": 0,
        "eyes": 0,
        "heart": 1,
        "hooray": 0,
        "laugh": 0,
        "rocket": 0,
        "total_count": 1,
        "url": "https://api.github.com/repos/neovim/neovim/issues/35124/reactions"
    },
    "repository_url": "https://api.github.com/repos/neovim/neovim",
    "state": "closed",
    "state_reason": "completed",
    "sub_issues_summary": {
        "completed": 0,
        "percent_completed": 0,
        "total": 0
    },
    "timeline_url": "https://api.github.com/repos/neovim/neovim/issues/35124/timeline",
    "title": "Broken oldtests in master",
    "type": {
        "color": "red",
        "created_at": "2024-01-25T10:10:19Z",
        "description": "An unexpected problem or behavior",
        "id": 597163,
        "is_enabled": true,
        "name": "Bug",
        "node_id": "IT_kwDOAGK_Pc4ACRyr",
        "updated_at": "2024-07-26T10:12:30Z"
    },
    "updated_at": "2025-08-02T09:51:42Z",
    "url": "https://api.github.com/repos/neovim/neovim/issues/35124",
    "user": {
        "avatar_url": "https://avatars.githubusercontent.com/u/5817809?v=4",
        "events_url": "https://api.github.com/users/antonk52/events{/privacy}",
        "followers_url": "https://api.github.com/users/antonk52/followers",
        "following_url": "https://api.github.com/users/antonk52/following{/other_user}",
        "gists_url": "https://api.github.com/users/antonk52/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/antonk52",
        "id": 5817809,
        "login": "antonk52",
        "node_id": "MDQ6VXNlcjU4MTc4MDk=",
        "organizations_url": "https://api.github.com/users/antonk52/orgs",
        "received_events_url": "https://api.github.com/users/antonk52/received_events",
        "repos_url": "https://api.github.com/users/antonk52/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/antonk52/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/antonk52/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/antonk52",
        "user_view_type": "public"
    }
}