{
    "active_lock_reason": null,
    "assignee": null,
    "assignees": [],
    "author_association": "CONTRIBUTOR",
    "body": "### Problem\n\nHi! After updating to the latest nightly/master I find a Vimscript utility I use stopped working with the following error message:\n\n```\nE471: Argument required:         con\n```\n\nNow, `:help :con` still opens the help text for `:continue`, but it seems it is now resolved to `:connect` instead. I could update my script to use `:cont` instead of `:con`, but I believe this must be a recent regression bug as there seems to be no good reason for this change. Also, the docs are not updated accordingly.\n\n\n### Steps to reproduce\n\n1. Create file `test.vim` with\n\n```vim\nfor s:i in range(5)\n  if s:i < 3\n    con\n  en\n  echo s:i\nendfo\n```\n\n2. Run `nvim -u test.vim`.\n\n### Expected behavior\n\n`con` should resolve to `continue`\n\n### Nvim version (nvim -v)\n\n0.12.0-dev-1024+g35a7642647\n\n### Vim (not Nvim) behaves the same?\n\nNo\n\n### Operating system/version\n\nArch Linux\n\n### Terminal name/version\n\nwezterm\n\n### $TERM environment variable\n\nxterm-256color\n\n### Installation\n\nAUR",
    "closed_at": "2025-08-19T07:15:13Z",
    "closed_by": {
        "avatar_url": "https://avatars.githubusercontent.com/u/998898?v=4",
        "events_url": "https://api.github.com/users/lervag/events{/privacy}",
        "followers_url": "https://api.github.com/users/lervag/followers",
        "following_url": "https://api.github.com/users/lervag/following{/other_user}",
        "gists_url": "https://api.github.com/users/lervag/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/lervag",
        "id": 998898,
        "login": "lervag",
        "node_id": "MDQ6VXNlcjk5ODg5OA==",
        "organizations_url": "https://api.github.com/users/lervag/orgs",
        "received_events_url": "https://api.github.com/users/lervag/received_events",
        "repos_url": "https://api.github.com/users/lervag/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/lervag/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/lervag/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/lervag",
        "user_view_type": "public"
    },
    "comment_data": [
        {
            "author_association": "CONTRIBUTOR",
            "body": "While writing the bug report I updated neovim again. With 0.12.0-dev-1039+g25bc41847e it seems that the bug is already fixed. Sorry for the noise!",
            "created_at": "2025-08-19T07:15:13Z",
            "html_url": "https://github.com/neovim/neovim/issues/35385#issuecomment-3199522203",
            "id": 3199522203,
            "issue_url": "https://api.github.com/repos/neovim/neovim/issues/35385",
            "node_id": "IC_kwDOAPphoM6-tNWb",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/neovim/neovim/issues/comments/3199522203/reactions"
            },
            "updated_at": "2025-08-19T07:15:13Z",
            "url": "https://api.github.com/repos/neovim/neovim/issues/comments/3199522203",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/998898?v=4",
                "events_url": "https://api.github.com/users/lervag/events{/privacy}",
                "followers_url": "https://api.github.com/users/lervag/followers",
                "following_url": "https://api.github.com/users/lervag/following{/other_user}",
                "gists_url": "https://api.github.com/users/lervag/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/lervag",
                "id": 998898,
                "login": "lervag",
                "node_id": "MDQ6VXNlcjk5ODg5OA==",
                "organizations_url": "https://api.github.com/users/lervag/orgs",
                "received_events_url": "https://api.github.com/users/lervag/received_events",
                "repos_url": "https://api.github.com/users/lervag/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/lervag/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/lervag/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/lervag",
                "user_view_type": "public"
            }
        },
        {
            "author_association": "CONTRIBUTOR",
            "body": "For reference, this was fixed in https://github.com/neovim/neovim/pull/35370 and the issue is essentially a duplicate of https://github.com/neovim/neovim/issues/35363.",
            "created_at": "2025-08-19T07:22:40Z",
            "html_url": "https://github.com/neovim/neovim/issues/35385#issuecomment-3199543113",
            "id": 3199543113,
            "issue_url": "https://api.github.com/repos/neovim/neovim/issues/35385",
            "node_id": "IC_kwDOAPphoM6-tSdJ",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/neovim/neovim/issues/comments/3199543113/reactions"
            },
            "updated_at": "2025-08-19T07:22:40Z",
            "url": "https://api.github.com/repos/neovim/neovim/issues/comments/3199543113",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/998898?v=4",
                "events_url": "https://api.github.com/users/lervag/events{/privacy}",
                "followers_url": "https://api.github.com/users/lervag/followers",
                "following_url": "https://api.github.com/users/lervag/following{/other_user}",
                "gists_url": "https://api.github.com/users/lervag/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/lervag",
                "id": 998898,
                "login": "lervag",
                "node_id": "MDQ6VXNlcjk5ODg5OA==",
                "organizations_url": "https://api.github.com/users/lervag/orgs",
                "received_events_url": "https://api.github.com/users/lervag/received_events",
                "repos_url": "https://api.github.com/users/lervag/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/lervag/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/lervag/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/lervag",
                "user_view_type": "public"
            }
        }
    ],
    "comments": 2,
    "comments_url": "https://api.github.com/repos/neovim/neovim/issues/35385/comments",
    "created_at": "2025-08-19T07:14:15Z",
    "events_url": "https://api.github.com/repos/neovim/neovim/issues/35385/events",
    "html_url": "https://github.com/neovim/neovim/issues/35385",
    "id": 3333202472,
    "issue_dependencies_summary": {
        "blocked_by": 0,
        "blocking": 0,
        "total_blocked_by": 0,
        "total_blocking": 0
    },
    "labels": [],
    "labels_url": "https://api.github.com/repos/neovim/neovim/issues/35385/labels{/name}",
    "locked": false,
    "milestone": null,
    "node_id": "I_kwDOAPphoM7GrKIo",
    "number": 35385,
    "performed_via_github_app": null,
    "reactions": {
        "+1": 0,
        "-1": 0,
        "confused": 0,
        "eyes": 0,
        "heart": 0,
        "hooray": 0,
        "laugh": 0,
        "rocket": 0,
        "total_count": 0,
        "url": "https://api.github.com/repos/neovim/neovim/issues/35385/reactions"
    },
    "repository_url": "https://api.github.com/repos/neovim/neovim",
    "state": "closed",
    "state_reason": "completed",
    "sub_issues_summary": {
        "completed": 0,
        "percent_completed": 0,
        "total": 0
    },
    "timeline_url": "https://api.github.com/repos/neovim/neovim/issues/35385/timeline",
    "title": ":con is mistakenly recognized as :connect instead of :continue",
    "type": {
        "color": "red",
        "created_at": "2024-01-25T10:10:19Z",
        "description": "An unexpected problem or behavior",
        "id": 597163,
        "is_enabled": true,
        "name": "Bug",
        "node_id": "IT_kwDOAGK_Pc4ACRyr",
        "updated_at": "2024-07-26T10:12:30Z"
    },
    "updated_at": "2025-08-19T07:22:40Z",
    "url": "https://api.github.com/repos/neovim/neovim/issues/35385",
    "user": {
        "avatar_url": "https://avatars.githubusercontent.com/u/998898?v=4",
        "events_url": "https://api.github.com/users/lervag/events{/privacy}",
        "followers_url": "https://api.github.com/users/lervag/followers",
        "following_url": "https://api.github.com/users/lervag/following{/other_user}",
        "gists_url": "https://api.github.com/users/lervag/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/lervag",
        "id": 998898,
        "login": "lervag",
        "node_id": "MDQ6VXNlcjk5ODg5OA==",
        "organizations_url": "https://api.github.com/users/lervag/orgs",
        "received_events_url": "https://api.github.com/users/lervag/received_events",
        "repos_url": "https://api.github.com/users/lervag/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/lervag/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/lervag/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/lervag",
        "user_view_type": "public"
    }
}