{
    "active_lock_reason": null,
    "assignee": null,
    "assignees": [],
    "author_association": "NONE",
    "body": "I have a Python script that is spawning thousands of short lived `nvim` instances.\r\nWith the latest release of pynvim  (i.e. `0.5.0`) the output gets flooded with the following messages: \r\n\r\n```\r\n…\r\nLoop <_UnixSelectorEventLoop running=False closed=True debug=False> that handles pid 40854 is closed\r\nLoop <_UnixSelectorEventLoop running=False closed=True debug=False> that handles pid 40855 is closed\r\nLoop <_UnixSelectorEventLoop running=False closed=True debug=False> that handles pid 40856 is closed\r\n…\r\n```\r\n\r\nIs there a way to silence these messages ? A workaround, for the time being, is to downgrade to `0.4.3`.\r\n\r\nThank you for your time and the new release.\r\n\r\nOutput of `nvim -V1 -v `\r\n\r\n```\r\nNVIM v0.10.0-dev-1157+g6e0e36bd70\r\nBuild type: RelWithDebInfo\r\nLuaJIT 2.1.1694940244\r\nCompilation: /Library/Developer/CommandLineTools/usr/bin/cc -O2 -g -Og -g -Wall -Wextra -ped\r\nantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wvla -Wdou\r\nble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -Wimplicit-\r\nfallthrough -fdiagnostics-color=always -fstack-protector-strong -DUNIT_TESTING -DINCLUDE_GEN\r\nERATED_DECLARATIONS -DNVIM_TS_HAS_SET_MAX_START_DEPTH -I/Users/pierreganty/neovim/.deps/usr/\r\ninclude/luajit-2.1 -I/opt/homebrew/opt/gettext/include -I/Users/pierreganty/neovim/.deps/usr\r\n/include -I/Users/pierreganty/neovim/build/src/nvim/auto -I/Users/pierreganty/neovim/build/i\r\nnclude -I/Users/pierreganty/neovim/build/cmake.config -I/Users/pierreganty/neovim/src -I/Lib\r\nrary/Developer/CommandLineTools/SDKs/MacOSX14.0.sdk/usr/include\r\n```",
    "closed_at": null,
    "closed_by": null,
    "comment_data": [
        {
            "author_association": "MEMBER",
            "body": "Questions:\r\n\r\n- Does that happen also on pynvim 0.4.3 or only on pynvim 0.5.0?\r\n- What is your python version?\r\n- Can you make a simple reproduction by any chance? That will be very helpful for debugging.\r\n\r\nThe warning is actually coming from `ChildWatcher`: https://github.com/python/cpython/blob/v3.12.0/Lib/asyncio/unix_events.py#L1333-L1334. I think there is some missing logic w.r.t the lifecycle of event loop when child processes (hence child watcher) are used. Relevant: #241 #543",
            "created_at": "2023-12-11T22:21:42Z",
            "html_url": "https://github.com/neovim/pynvim/issues/555#issuecomment-1850985723",
            "id": 1850985723,
            "issue_url": "https://api.github.com/repos/neovim/pynvim/issues/555",
            "node_id": "IC_kwDOASpKTs5uU8z7",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/neovim/pynvim/issues/comments/1850985723/reactions"
            },
            "updated_at": "2023-12-11T22:45:36Z",
            "url": "https://api.github.com/repos/neovim/pynvim/issues/comments/1850985723",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/1009873?v=4",
                "events_url": "https://api.github.com/users/wookayin/events{/privacy}",
                "followers_url": "https://api.github.com/users/wookayin/followers",
                "following_url": "https://api.github.com/users/wookayin/following{/other_user}",
                "gists_url": "https://api.github.com/users/wookayin/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/wookayin",
                "id": 1009873,
                "login": "wookayin",
                "node_id": "MDQ6VXNlcjEwMDk4NzM=",
                "organizations_url": "https://api.github.com/users/wookayin/orgs",
                "received_events_url": "https://api.github.com/users/wookayin/received_events",
                "repos_url": "https://api.github.com/users/wookayin/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/wookayin/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/wookayin/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/wookayin",
                "user_view_type": "public"
            }
        },
        {
            "author_association": "NONE",
            "body": "1. Does not happen in 0.4.3, only in 0.5.0\r\n2. Python 3.11.6\r\n3. I am not able to come up with a simple reproduction and won't be able to look into it in 2023.",
            "created_at": "2023-12-11T22:25:28Z",
            "html_url": "https://github.com/neovim/pynvim/issues/555#issuecomment-1850989957",
            "id": 1850989957,
            "issue_url": "https://api.github.com/repos/neovim/pynvim/issues/555",
            "node_id": "IC_kwDOASpKTs5uU92F",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/neovim/pynvim/issues/comments/1850989957/reactions"
            },
            "updated_at": "2023-12-11T22:25:28Z",
            "url": "https://api.github.com/repos/neovim/pynvim/issues/comments/1850989957",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/2111160?v=4",
                "events_url": "https://api.github.com/users/pierreganty/events{/privacy}",
                "followers_url": "https://api.github.com/users/pierreganty/followers",
                "following_url": "https://api.github.com/users/pierreganty/following{/other_user}",
                "gists_url": "https://api.github.com/users/pierreganty/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/pierreganty",
                "id": 2111160,
                "login": "pierreganty",
                "node_id": "MDQ6VXNlcjIxMTExNjA=",
                "organizations_url": "https://api.github.com/users/pierreganty/orgs",
                "received_events_url": "https://api.github.com/users/pierreganty/received_events",
                "repos_url": "https://api.github.com/users/pierreganty/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/pierreganty/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/pierreganty/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/pierreganty",
                "user_view_type": "public"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "Without a reasonable reproduction, bugfix might take a bit long. Please let us know when you've got some free cycles.\r\n\r\nMy guess is that fd4247ced2b536c82fe76c52a6a6042eebb31ad4 is the relevant difference against 0.4.3. I have a proposed fix: a PR will follow (EDIT: #556), please stay tuned.",
            "created_at": "2023-12-11T22:33:59Z",
            "html_url": "https://github.com/neovim/pynvim/issues/555#issuecomment-1850999413",
            "id": 1850999413,
            "issue_url": "https://api.github.com/repos/neovim/pynvim/issues/555",
            "node_id": "IC_kwDOASpKTs5uVAJ1",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/neovim/pynvim/issues/comments/1850999413/reactions"
            },
            "updated_at": "2023-12-11T22:36:05Z",
            "url": "https://api.github.com/repos/neovim/pynvim/issues/comments/1850999413",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/1009873?v=4",
                "events_url": "https://api.github.com/users/wookayin/events{/privacy}",
                "followers_url": "https://api.github.com/users/wookayin/followers",
                "following_url": "https://api.github.com/users/wookayin/following{/other_user}",
                "gists_url": "https://api.github.com/users/wookayin/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/wookayin",
                "id": 1009873,
                "login": "wookayin",
                "node_id": "MDQ6VXNlcjEwMDk4NzM=",
                "organizations_url": "https://api.github.com/users/wookayin/orgs",
                "received_events_url": "https://api.github.com/users/wookayin/received_events",
                "repos_url": "https://api.github.com/users/wookayin/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/wookayin/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/wookayin/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/wookayin",
                "user_view_type": "public"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "Hmm if https://github.com/neovim/pynvim/pull/556#issuecomment-1851031322 doesn't fix this, I'll need a repro to help you troubleshoot this issue. At least any traceback information will be needed.\r\n\r\nCan you try enabling neovim logging?\r\n\r\n```bash\r\n$ export NVIM_PYTHON_LOG_FILE=\"555.log\" NVIM_PYTHON_LOG_LEVEL=\"debug\"\r\n$ python ...<your script>...\r\n```\r\n\r\nor override asyncio's warning logger to print the detailed stacktrace information:\r\n\r\n```python\r\nimport functools\r\nimport logging\r\nimport asyncio.log\r\nformatter = logging.Formatter('[%(levelname)s %(asctime)s] %(filename)s:%(lineno)d %(message)s')\r\nch = logging.StreamHandler()\r\nch.setFormatter(formatter)\r\nasyncio.log.logger.addHandler(ch)\r\nasyncio.log.logger.warning = functools.partial(asyncio.log.logger.warning, stack_info=True)\r\n```\r\n\r\nBTW, if you'd like to silence the warning you can do something like:\r\n\r\n```python\r\nimport asyncio.log\r\nasyncio.log.logger.setLevel(\"ERROR\")\r\n```",
            "created_at": "2023-12-11T23:38:50Z",
            "html_url": "https://github.com/neovim/pynvim/issues/555#issuecomment-1851068395",
            "id": 1851068395,
            "issue_url": "https://api.github.com/repos/neovim/pynvim/issues/555",
            "node_id": "IC_kwDOASpKTs5uVQ_r",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/neovim/pynvim/issues/comments/1851068395/reactions"
            },
            "updated_at": "2023-12-11T23:39:03Z",
            "url": "https://api.github.com/repos/neovim/pynvim/issues/comments/1851068395",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/1009873?v=4",
                "events_url": "https://api.github.com/users/wookayin/events{/privacy}",
                "followers_url": "https://api.github.com/users/wookayin/followers",
                "following_url": "https://api.github.com/users/wookayin/following{/other_user}",
                "gists_url": "https://api.github.com/users/wookayin/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/wookayin",
                "id": 1009873,
                "login": "wookayin",
                "node_id": "MDQ6VXNlcjEwMDk4NzM=",
                "organizations_url": "https://api.github.com/users/wookayin/orgs",
                "received_events_url": "https://api.github.com/users/wookayin/received_events",
                "repos_url": "https://api.github.com/users/wookayin/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/wookayin/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/wookayin/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/wookayin",
                "user_view_type": "public"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "Minimal repro:\r\n```python\r\nvim = pynvim.attach('child', argv=['nvim', '--embed', '--clean', '-i', 'NONE'])\r\nvim.close()\r\nvim = pynvim.attach('child', argv=['nvim', '--embed', '--clean', '-i', 'NONE'])\r\nvim.close()\r\n\r\n# Result\r\nLoop <_UnixSelectorEventLoop running=False closed=True debug=False> that handles pid 1048 is closed\r\n```",
            "created_at": "2023-12-12T03:11:57Z",
            "html_url": "https://github.com/neovim/pynvim/issues/555#issuecomment-1851232780",
            "id": 1851232780,
            "issue_url": "https://api.github.com/repos/neovim/pynvim/issues/555",
            "node_id": "IC_kwDOASpKTs5uV5IM",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 2,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 2,
                "url": "https://api.github.com/repos/neovim/pynvim/issues/comments/1851232780/reactions"
            },
            "updated_at": "2023-12-12T03:11:57Z",
            "url": "https://api.github.com/repos/neovim/pynvim/issues/comments/1851232780",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/1009873?v=4",
                "events_url": "https://api.github.com/users/wookayin/events{/privacy}",
                "followers_url": "https://api.github.com/users/wookayin/followers",
                "following_url": "https://api.github.com/users/wookayin/following{/other_user}",
                "gists_url": "https://api.github.com/users/wookayin/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/wookayin",
                "id": 1009873,
                "login": "wookayin",
                "node_id": "MDQ6VXNlcjEwMDk4NzM=",
                "organizations_url": "https://api.github.com/users/wookayin/orgs",
                "received_events_url": "https://api.github.com/users/wookayin/received_events",
                "repos_url": "https://api.github.com/users/wookayin/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/wookayin/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/wookayin/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/wookayin",
                "user_view_type": "public"
            }
        }
    ],
    "comments": 5,
    "comments_url": "https://api.github.com/repos/neovim/pynvim/issues/555/comments",
    "created_at": "2023-12-11T18:18:14Z",
    "events_url": "https://api.github.com/repos/neovim/pynvim/issues/555/events",
    "html_url": "https://github.com/neovim/pynvim/issues/555",
    "id": 2036263233,
    "issue_dependencies_summary": {
        "blocked_by": 0,
        "blocking": 0,
        "total_blocked_by": 0,
        "total_blocking": 0
    },
    "labels": [],
    "labels_url": "https://api.github.com/repos/neovim/pynvim/issues/555/labels{/name}",
    "locked": false,
    "milestone": null,
    "node_id": "I_kwDOASpKTs55XulB",
    "number": 555,
    "performed_via_github_app": null,
    "reactions": {
        "+1": 0,
        "-1": 0,
        "confused": 0,
        "eyes": 0,
        "heart": 0,
        "hooray": 0,
        "laugh": 0,
        "rocket": 0,
        "total_count": 0,
        "url": "https://api.github.com/repos/neovim/pynvim/issues/555/reactions"
    },
    "repository_url": "https://api.github.com/repos/neovim/pynvim",
    "state": "open",
    "state_reason": null,
    "sub_issues_summary": {
        "completed": 0,
        "percent_completed": 0,
        "total": 0
    },
    "timeline_url": "https://api.github.com/repos/neovim/pynvim/issues/555/timeline",
    "title": "Output flooded with EventLoop related messages ",
    "type": {
        "color": "red",
        "created_at": "2024-01-25T10:10:19Z",
        "description": "An unexpected problem or behavior",
        "id": 597163,
        "is_enabled": true,
        "name": "Bug",
        "node_id": "IT_kwDOAGK_Pc4ACRyr",
        "updated_at": "2024-07-26T10:12:30Z"
    },
    "updated_at": "2025-09-22T19:33:16Z",
    "url": "https://api.github.com/repos/neovim/pynvim/issues/555",
    "user": {
        "avatar_url": "https://avatars.githubusercontent.com/u/2111160?v=4",
        "events_url": "https://api.github.com/users/pierreganty/events{/privacy}",
        "followers_url": "https://api.github.com/users/pierreganty/followers",
        "following_url": "https://api.github.com/users/pierreganty/following{/other_user}",
        "gists_url": "https://api.github.com/users/pierreganty/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/pierreganty",
        "id": 2111160,
        "login": "pierreganty",
        "node_id": "MDQ6VXNlcjIxMTExNjA=",
        "organizations_url": "https://api.github.com/users/pierreganty/orgs",
        "received_events_url": "https://api.github.com/users/pierreganty/received_events",
        "repos_url": "https://api.github.com/users/pierreganty/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/pierreganty/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/pierreganty/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/pierreganty",
        "user_view_type": "public"
    }
}